# Generated by Django 2.2.7 on 2019-11-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=8)),
                ('delivered', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Requestmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField()),
                ('graphic_type', models.CharField(choices=[('Poster', 'poster'), ('Icon', 'icon'), ('Logo', 'logo'), ('Different', 'different')], default='Logo', max_length=9)),
                ('deadline', models.DateTimeField()),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('wireframe', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
