# Generated by Django 2.2.7 on 2019-11-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Designer', 'I want to design'), ('User', 'I want to buy designs')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Quotes',
        ),
        migrations.DeleteModel(
            name='Requestmodel',
        ),
    ]
