# Generated by Django 2.2.7 on 2019-11-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20191127_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
