# Generated by Django 2.2.7 on 2019-11-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
